"""Added donor weight and next eligible date

Revision ID: 768015329887
Revises: a78c4677babc
Create Date: 2026-08-06 17:53:53.572143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768015329887'
down_revision = 'a78c4677babc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('next_eligible_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('next_eligible_date')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
