"""Add response deadline

Revision ID: 76dca7c4145b
Revises: 8826f32908a7
Create Date: 2026-07-21 20:22:41.798728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dca7c4145b'
down_revision = '8826f32908a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_matches', schema=None) as batch_op:
        batch_op.drop_column('response_deadline')

    # ### end Alembic commands ###
