"""add hospital and inventory management

Revision ID: 8333d5148cb6
Revises: 4bd32c6f5734
Create Date: 2026-08-13 22:27:26.542036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8333d5148cb6'
down_revision = '4bd32c6f5734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('available_units', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('available_units >= 0', name='check_positive_units'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('hospital_id', 'blood_group', name='uq_hospital_blood_group')
    )
    op.create_table('blood_inventory_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('ADD', 'REMOVE', 'RESERVATION', 'RELEASE', 'FULFILLMENT'), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['blood_inventory.inventory_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.request_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['hospital_id'])

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'DONOR', 'PATIENT'),
               type_=sa.Enum('ADMIN', 'DONOR', 'PATIENT', 'HOSPITAL'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'DONOR', 'PATIENT', 'HOSPITAL'),
               type_=mysql.ENUM('ADMIN', 'DONOR', 'PATIENT'),
               existing_nullable=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hospital_id')

    op.drop_table('blood_inventory_transactions')
    op.drop_table('blood_inventory')
    # ### end Alembic commands ###
