"""Initial database

Revision ID: 9a8eac86e3cb
Revises: 
Create Date: 2026-07-18 23:17:07.819348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8eac86e3cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DONOR', 'PATIENT'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('donors',
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('total_donations', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('donor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other'), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('badges',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('badge_description', sa.String(length=255), nullable=True),
    sa.Column('badge_icon', sa.String(length=255), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('blood_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('emergency_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=False),
    sa.Column('hospital_latitude', sa.Float(), nullable=True),
    sa.Column('hospital_longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Matched', 'Accepted', 'Completed', 'Cancelled'), nullable=True),
    sa.Column('request_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('reward_points',
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('earned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.PrimaryKeyConstraint('reward_id')
    )
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('donation_date', sa.Date(), nullable=False),
    sa.Column('units_donated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.request_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('donor_matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('response_probability', sa.Float(), nullable=False),
    sa.Column('ranking_score', sa.Float(), nullable=False),
    sa.Column('donor_response', sa.Enum('Pending', 'Accepted', 'Rejected'), nullable=False),
    sa.Column('matched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.request_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('response_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Enum('Accepted', 'Rejected', 'Missed'), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.request_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'DANGER'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_request_id', sa.Integer(), nullable=True),
    sa.Column('related_match_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_match_id'], ['donor_matches.match_id'], ),
    sa.ForeignKeyConstraint(['related_request_id'], ['blood_requests.request_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('response_history')
    op.drop_table('donor_matches')
    op.drop_table('donations')
    op.drop_table('reward_points')
    op.drop_table('feedback')
    op.drop_table('blood_requests')
    op.drop_table('badges')
    op.drop_table('patients')
    op.drop_table('donors')
    op.drop_table('users')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
