"""patient model update

Revision ID: a78c4677babc
Revises: d17c5e647247
Create Date: 2026-08-05 11:32:57.640675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a78c4677babc'
down_revision = 'd17c5e647247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('Pending', 'Accepted', 'Completed', 'Cancelled'),
               type_=sa.Enum('Pending', 'Matched', 'Accepted', 'Completed', 'Cancelled'),
               existing_nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('blood_group',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Other'),
               nullable=True)
        batch_op.alter_column('hospital_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('hospital_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Other'),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('blood_group',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'Matched', 'Accepted', 'Completed', 'Cancelled'),
               type_=mysql.ENUM('Pending', 'Accepted', 'Completed', 'Cancelled'),
               existing_nullable=True)

    # ### end Alembic commands ###
