"""add last_response_time

Revision ID: b0fefad954a7
Revises: 768015329887
Create Date: 2026-08-11 20:45:30.017174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0fefad954a7'
down_revision = '768015329887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_matches', schema=None) as batch_op:
        batch_op.alter_column('donor_response',
               existing_type=mysql.ENUM('Pending', 'Accepted', 'Rejected'),
               type_=sa.Enum('Pending', 'Accepted', 'Rejected', 'Missed'),
               existing_nullable=False)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_response_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('successful_donations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_requests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accepted_requests', sa.Integer(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('notification_type')
        batch_op.drop_column('title')

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('accepted_requests')
        batch_op.drop_column('rejected_requests')
        batch_op.drop_column('successful_donations')
        batch_op.drop_column('last_response_time')

    with op.batch_alter_table('donor_matches', schema=None) as batch_op:
        batch_op.alter_column('donor_response',
               existing_type=sa.Enum('Pending', 'Accepted', 'Rejected', 'Missed'),
               type_=mysql.ENUM('Pending', 'Accepted', 'Rejected'),
               existing_nullable=False)

    # ### end Alembic commands ###
