"""Added reward_points and badge to donor

Revision ID: c21ca26cf691
Revises: 76dca7c4145b
Create Date: 2026-08-03 21:46:40.466702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c21ca26cf691'
down_revision = '76dca7c4145b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospitals')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('badge', sa.String(length=50), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('notifications_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('related_match_id')
        batch_op.drop_column('type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.ENUM('INFO', 'SUCCESS', 'WARNING', 'DANGER'), nullable=True))
        batch_op.add_column(sa.Column('related_match_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('notifications_ibfk_1'), 'donor_matches', ['related_match_id'], ['match_id'])
        batch_op.alter_column('is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('badge')
        batch_op.drop_column('reward_points')

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    op.create_table('hospitals',
    sa.Column('hospital_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hospital_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=False),
    sa.Column('longitude', mysql.FLOAT(), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pincode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
