"""add hospital transfers table

Revision ID: cd8961f8ec6b
Revises: 8333d5148cb6
Create Date: 2026-08-13 23:15:37.119999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8961f8ec6b'
down_revision = '8333d5148cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_transfers',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('source_hospital_id', sa.Integer(), nullable=False),
    sa.Column('destination_hospital_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units_requested', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.request_id'], ),
    sa.ForeignKeyConstraint(['source_hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_transfers')
    # ### end Alembic commands ###
