"""Add donation status

Revision ID: d17c5e647247
Revises: c21ca26cf691
Create Date: 2026-08-04 21:32:36.681147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd17c5e647247'
down_revision = 'c21ca26cf691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('Pending', 'Matched', 'Accepted', 'Completed', 'Cancelled'),
               type_=sa.Enum('Pending', 'Accepted', 'Completed', 'Cancelled'),
               existing_nullable=True)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_status', sa.Enum('Pending', 'Completed'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('donation_status')

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'Accepted', 'Completed', 'Cancelled'),
               type_=mysql.ENUM('Pending', 'Matched', 'Accepted', 'Completed', 'Cancelled'),
               existing_nullable=True)

    # ### end Alembic commands ###
